GRAM = {"fr": {"imper": 8, "rel": 13, "cond": 15, "si": 16, "subj": 17, "err": 18,
               "tid": 2, "quel": 3, "proche": 5, "nombre": 7, "dem": 11, "tout": 14, "ger": 17}}
for c in ["frs4", "frs5", "fr4", "de4", "de6"]: GRAM[c] = {"err": 17}

TITLES = {"fr": "Studieplan för Franska 3", "frs4": "Studieplan för Franska 4", "frs5": "Studieplan för Franska 5",
          "fr4": "Studieplan för Franska 6", "de4": "Studieplan för Tyska 4", "de6": "Studieplan för Tyska 6"}
_self = "Räkna med ungefär 3–4 timmar i veckan: ett glospass varje dag och resten av veckans uppgifter utspritt. Hinner du inte en vecka gör det inget, fortsätt där du är."
INTRO = {
 "fr": "Ett förslag på hur du kan gå igenom Franska 3 på en termin (19 veckor), i samma ordning som bokens kapitel. Varje vecka har nya ord, grammatik och texter; bokens egna texter och övningar gör ni på lektionerna. Musikteorin är valfri och ingår inte. Följer klassen en annan takt, välj den vecka ni är på.",
 "frs4": "Ett förslag på hur du kan läsa hela Franska 4 på en termin (18 veckor): två veckor per kapitel och sist repetition och provträning inför DELF A2. " + _self,
 "frs5": "Ett förslag på hur du kan läsa hela Franska 5 på en termin (18 veckor): två veckor per kapitel och sist repetition och provträning inför DELF B1. " + _self,
 "fr4": "Ett förslag på hur du kan läsa hela Franska 6 på en termin (18 veckor): två veckor per kapitel och sist repetition och en provsimulering inför DELF B1. " + _self,
 "de4": "Ett förslag på hur du kan läsa hela Tyska 4 på en termin (18 veckor): två veckor per kapitel och sist repetition och provträning inför Goethe-Zertifikat B1. " + _self,
 "de6": "Ett förslag på hur du kan läsa hela Tyska 6 på en termin (18 veckor): två veckor per kapitel och sist repetition och en provsimulering inför B2-provet. " + _self,
}

TIPS = {
 "fr": [
  "Börja med jämförelser (plus … que) och reflexiva verb. Säg verben högt med pronomenet: je me lève, tu te lèves.",
  "Lyssna på hörtexterna två gånger: först för helheten, sedan för detaljerna.",
  "Avsluta kapitel 1 med kapitelprovet och öva sedan på orden du missade.",
  "Passé composé: tänk på DR MRS VANDERTRAMP-verben som tar être. Betonade pronomen (moi, toi) kommer ofta efter prepositioner.",
  "Skriv veckans text med minst tre verb i passé composé. Läs den högt när du är klar.",
  "Du, de la, des: efter negation blir det bara de. Öva adjektivens böjning i samma veva.",
  "Aller-gruppen tar être i passé composé. Gör kapitelprovet för kapitel 3 i slutet av veckan.",
  "Pronomen som le, lui, y och en står före verbet. Imperativ: Viens ! Allons-y !",
  "Possessiva pronomen och stor eller liten bokstav (français, le Français). Kapitelprovet för kapitel 4 i slutet av veckan.",
  "Negationen omsluter verbet: ne … pas, ne … jamais, ne … plus. Två korta kapitel den här veckan.",
  "Prepositioner med länder och städer: en France, au Canada, à Paris.",
  "Imparfait för bakgrund och vanor, passé composé för det som hände. Gör kapitelprovet för kapitel 7.",
  "Qui, que, où, dont binder ihop meningar. Frågor och futur: öva att fråga om framtidsplaner.",
  "Repetera kapitel 8 och gör kapitelprovet. Skriv några meningar om vad du ska göra i sommar.",
  "Conditionnel för önskemål och artiga frågor: je voudrais, tu pourrais.",
  "Si-satser: si + presens → futur, si + imparfait → conditionnel.",
  "Subjonctif efter il faut que och je veux que. Avsluta kapitel 12 med kapitelprovet.",
  "Hitta felet blandar allt. Gå igenom orden du har svårt för och provträna på delarna du tycker är svårast.",
  "Gör en hel provsimulering med klocka. Jämför med förra gången och repetera det som gick sämst.",
 ],
 "frs4": [
  "Plus-que-parfait = det som hade hänt före något annat i dåtid. Sätt upp ett fast pass varje dag, gärna 20–30 minuter.",
  "Conditionnel för drömmar och planer: je voudrais, j'aimerais. Avsluta kapitlet med kapitelprovet.",
  "Si-satser: si + imparfait → conditionnel. Läs texterna högt för att öva uttalet.",
  "Dubbla pronomen har fast ordning: me le, le lui, y en. Gör frågorna i små omgångar.",
  "Dont, ce qui och ce que binder ihop meningar. Leta efter dem i veckans lästext.",
  "Sambandsord (d'abord, ensuite, pourtant) gör texten lättare att följa. Använd minst tre i veckans text.",
  "Fester och traditioner: jämför med hur ni firar hemma när du skriver.",
  "Avsluta kapitel 4 med kapitelprovet och repetera orden du missade.",
  "Verb + à/de + infinitiv (commencer à, essayer de) måste läras in med prepositionen.",
  "Il faut que + subjonctif: lär dig formerna för de vanligaste verben (fasse, aille, soit).",
  "Indirekt tal i presens: il dit que … Återberätta en hörtext med egna ord.",
  "Reklam och medier: läs med en penna och stryk under ord du vill spara.",
  "Film och litteratur: skriv några meningar om en film du gillar.",
  "Repetera grammatiken från kapitel 1–3 med Hitta felet om du har tid.",
  "Miljö och resor: öva på att ge råd och argumentera (il faudrait, on devrait).",
  "Sista kapitlet. Gör kapitelprovet och gå igenom orden du fortfarande har svårt för.",
  "Hitta felet blandar alla områden. Provträna på delarna i DELF A2 du tycker är svårast.",
  "Gör en hel provsimulering med klocka och repetera det som gick sämst.",
 ],
 "frs5": [
  "Subjonctif i vanliga fall (il faut que, bien que, pour que). Sätt upp ett fast pass varje dag.",
  "Bindeord för mål, motsats och medgivande gör argumenten tydligare. Avsluta kapitlet med kapitelprovet.",
  "Conditionnel passé: det som hade kunnat hända (j'aurais aimé).",
  "Si + plus-que-parfait → conditionnel passé: si j'avais su, je serais venu.",
  "Passiv: être + particip, och agenten med par. Leta efter passiv i veckans lästext.",
  "Vetenskapstexter har många lånord. Använd sammanfattningen för att träna både läsning och skrivning.",
  "Gérondif (en faisant) visar att två saker händer samtidigt eller hur något görs.",
  "Avsluta kapitel 4 med kapitelprovet och öva på orden du missade.",
  "Participets kongruens med avoir: la chanson que j'ai écoutée. Skriv långsamt och kontrollera ändelserna.",
  "Indirekt tal i dåtid: il a dit qu'il viendrait. Återberätta en hörtext med egna ord.",
  "Fiktion: läs novellen högt och lägg märke till passé simple, som bara ska kännas igen.",
  "Repetera grammatiken från kapitel 1–3 med Hitta felet om du har tid.",
  "Musik och konst: skriv om en konsert eller en låt du tycker om.",
  "Använd uttrycken för att nyansera och reagera när du skriver och talar.",
  "Konsumtion: öva på att väga för- och nackdelar i en text.",
  "Sista kapitlet. Gör kapitelprovet och gå igenom orden du fortfarande har svårt för.",
  "Hitta felet blandar alla områden. Provträna på de delar av DELF B1 som känns svårast.",
  "Gör en hel provsimulering med klocka och repetera det som gick sämst.",
 ],
 "fr4": [
  "Si-satser av alla tre typerna och conditionnel passé. Sätt upp ett fast pass varje dag, gärna 30 minuter.",
  "Futur antérieur: quand j'aurai fini, … Avsluta kapitlet med kapitelprovet.",
  "Lequel, auquel, duquel och dont: öva i små omgångar och läs regeln först.",
  "Indirekt tal och tidsföljd: återberätta en hörtext i dåtid med egna ord.",
  "Passiv: être + particip. Leta efter passiv i veckans texter om miljö och samhälle.",
  "Bindeord i argumentation (en revanche, néanmoins). Använd minst fyra i veckans text.",
  "Gérondif och participe présent gör texten mer varierad. Lyssna på hörtexten utan att läsa först.",
  "Framhävning med c'est … qui och ce qui/ce que. Avsluta kapitel 4 med kapitelprovet.",
  "Att bo och arbeta utomlands: skriv som om du söker en plats på ett konservatorium.",
  "Formella brev har fasta fraser. Samla dem i Mina ord.",
  "Passé simple ska du bara känna igen: il fut, ils eurent. Läs den litterära texten högt.",
  "Repetera grammatiken från kapitel 1–5 med Hitta felet om du har tid.",
  "Subjonctif: fler fall (bien que, avant que, à moins que). Gör frågorna i små omgångar.",
  "Subjonctif passé: je suis content que tu sois venu. Avsluta kapitel 7 med kapitelprovet.",
  "Etik och frankofoni: öva på att argumentera för och emot i en längre text.",
  "Sista kapitlet. Gör kapitelprovet och gå igenom orden du fortfarande har svårt för.",
  "Hitta felet blandar alla områden. Provträna på de delar av DELF B1 som känns svårast.",
  "Gör en hel provsimulering med klocka och jämför med DELF:s gräns för godkänt (50 av 100).",
 ],
 "de4": [
  "Perfekt: haben eller sein, och partizipet sist. Sätt upp ett fast pass varje dag, gärna 20–30 minuter.",
  "Ordföljd: verbet på plats två i huvudsats och sist i bisats. Avsluta kapitlet med kapitelprovet.",
  "Prepositioner med dativ eller ackusativ: wo? ger dativ, wohin? ger ackusativ.",
  "zu-infinitiv: Ich habe keine Lust, … zu … Skriv veckans text med några sådana meningar.",
  "Adjektivändelser: börja med tabellen efter der/die/das och öva lite varje dag.",
  "Avsluta kapitel 3 med kapitelprovet och öva sedan på orden du missade.",
  "Genitiv: des Mannes, der Stadt. Används mest i skrift och efter wegen och trotz.",
  "Reseord: öva på att fråga efter vägen och köpa biljett. Kapitelprovet i slutet av veckan.",
  "Präteritum används när man berättar i skrift. als, wenn, dass och ob styr bisatser.",
  "Futur I: werden + infinitiv. Skriv om dina planer efter gymnasiet.",
  "Verb med preposition (sich freuen auf, denken an) måste läras in med prepositionen. Jämförelser: größer als, am größten.",
  "Konjunktiv II för önskningar och artiga frågor: ich hätte gern, könntest du …",
  "Reflexiva verb: sich fühlen, sich erholen. Kroppsord övar du bäst med exempelmeningarna.",
  "Avsluta kapitel 7 med kapitelprovet och repetera orden du missade.",
  "Relativsatser: der Mann, der … Läs regeln först och gör sedan frågorna i små omgångar.",
  "Passiv: werden + particip. Sista kapitlet, avsluta med kapitelprovet.",
  "Hitta felet blandar alla områden. Provträna på de delar av Goethe B1 som känns svårast.",
  "Gör en hel provsimulering med klocka och repetera det som gick sämst.",
 ],
 "de6": [
  "Nominalstil gör texten formell: die Entscheidung statt entscheiden. Sätt upp ett fast pass varje dag, gärna 30 minuter.",
  "Nomen-Verb-Verbindungen (eine Entscheidung treffen) lärs in som helheter. Avsluta kapitlet med kapitelprovet.",
  "Indirekt tal med Konjunktiv I och Futur I och II. Leta efter dem i nyhetstexter.",
  "Passiversatz: sich lassen, sein + zu, -bar. Gör frågorna i små omgångar.",
  "Prepositioner med genitiv (trotz, während, aufgrund) är vanliga i formell text.",
  "Modalverb som bedömning: Er soll reich sein, sie muss es gewusst haben. Kapitelprovet i slutet av veckan.",
  "Konjunktiv II i dåtid: hätte gemacht, wäre gegangen. Läs den litterära texten högt.",
  "Utbyggda particip-attribut: der von Goethe geschriebene Roman. Läs dem bakifrån.",
  "Tillståndspassiv: Die Tür ist geschlossen. Jämför med vanligt passiv.",
  "Arbete och ekonomi: skriv veckans text formellt och använd nominalstil där det passar.",
  "Modalpartiklar (doch, mal, ja, eben) gör talet naturligt. Lyssna efter dem i hörtexterna.",
  "Avsluta kapitel 6 med kapitelprovet och öva på orden du missade.",
  "Konnektorer och textbindning gör argumenten tydliga. Använd minst fyra i veckans text.",
  "Filosofiska texter är täta. Läs en gång för helheten och en gång med ordlistan.",
  "Migration och stad och land: öva på att referera en text och ta ställning.",
  "Sista kapitlet. Gör kapitelprovet och gå igenom orden du fortfarande har svårt för.",
  "Hitta felet blandar alla områden. Provträna på de delar av B2-provet som känns svårast.",
  "Gör en hel provsimulering med klocka och repetera det som gick sämst.",
 ],
}
